# ieeg
```{r setup, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE
)
  library(dplyr)
  library(ggplot2)
  library(ggExtra)
  library(stringr)
  library(readr)
  library(ggplotify)  
proj_root <- rprojroot::find_root(rprojroot::has_file_pattern("\\.Rproj$"))
knitr::opts_knit$set(root.dir = proj_root)
```


## PostcentralL
### Functions
```{r}
# ---------- functions -----
source('analysis/06_ieeg/pearson_utils.R')
```


### Input
```{r}
# ---------- paths ----------
behavior_csv <- "data/06_ieeg/behavior_ieeg.csv"
feature_PostcentralL_csv  <- "data/06_ieeg/feature/ieeg_PostcentralL.csv"   
out_dir_fig  <- "figures/06_ieeg/PostcentralL"
out_dir_csv  <- "results/06_ieeg/ieeg_PostcentralL_pearson.csv"

# ---------- analysis params ----------
condition_keep <- c(
  "Voluntary_OutcomeOnsetReportSound",
  "Involuntary_OutcomeOnsetReportSound"
)

feature_cols <- c(
  "Alpha_bandPower",
  "Gamma_bandPower",
  "Beta_bandPower",
  "Delta_bandPower",
  "meanAmplitude"
)

```

### Pearson results
```{r}
dat_list_PostcentralL <- read_behavior_feature(
  behavior_csv = behavior_csv,
  feature_csv = feature_PostcentralL_csv,
  feature_encoding = "UTF-8"
)

joined_long_PostcentralL <- make_long_joined_df(
  be_df = dat_list_PostcentralL$be_df,
  feature_df = dat_list_PostcentralL$feature_df,
  feature_cols = feature_cols,
  condition_keep = condition_keep
)


pearson_res_PostcentralL <- compute_pearson_results(
  joined_long_df = joined_long_PostcentralL
)

pearson_res_PostcentralL %>% arrange(condition, feature) %>% head(20)
```
### Plot
```{r}
# ---------- plot style (optional) ----------
label_cols <- c(
  "chan61-chan62" = "#02c39a",
  "chan64-chan65" = "#ff758f",
  "chan78-chan79" = "#4a8fe7"
)

label_shapes <- c(
  "chan61-chan62" = 16,
  "chan64-chan65" = 17,
  "chan78-chan79" = 15
)

cond_plot <- "Voluntary_OutcomeOnsetReportSound"

# Alpha plot (no right marginal, no legend)
alpha_plot_PostcentralL <- make_scatter_marginal_plot(
  joined_long_df = joined_long_PostcentralL,
  condition_pick = cond_plot,
  feature_pick = "Alpha_bandPower",
  label_cols = label_cols,
  label_shapes = label_shapes,
  show_y_title = TRUE,
  show_legend = FALSE,
  show_right_margin = FALSE
)

# Gamma plot (with right marginal, no y title)
gamma_plot_PostcentralL <- make_scatter_marginal_plot(
  joined_long_df = joined_long_PostcentralL,
  condition_pick = cond_plot,
  feature_pick = "Gamma_bandPower",
  label_cols = label_cols,
  label_shapes = label_shapes,
  show_y_title = FALSE,
  show_legend = FALSE,
  show_right_margin = TRUE
)
```


### Save
```{r}
write_csv(pearson_res_PostcentralL, out_dir_csv)

ggsave(
    filename = file.path(out_dir_fig, "alpha_band_power.pdf"),
    plot = alpha_plot_PostcentralL,
    width = 9, height = 7, units = "in",
    device = cairo_pdf,
    family = "Arial"
  )

ggsave(
    filename = file.path(out_dir_fig, "gamma_band_power.pdf"),
    plot = gamma_plot_PostcentralL,
    width = 9, height = 7, units = "in",
    device = cairo_pdf,
    family = "Arial"
  )

```


## MTGR
### Plot
```{r}
feature_df_MTGR <- read_csv("data/06_ieeg/feature/ieeg_MTGR.csv",locale = readr::locale(encoding = "UTF-8"),show_col_types = FALSE)
be_df <- read_csv(behavior_csv,locale=readr::locale(encoding = "UTF-8"),show_col_types = FALSE)

condition_pick <- "Voluntary_OutcomeOnsetReportSound"

map_df <- tibble::tibble(
  subject = c("2", "4"),
  label   = c("chan81-chan82", "chan10-chan11")
)

# Colors must be named by the final x_label levels.
# Easiest: build once, then name accordingly:
x_lab_map <- build_itpc_xlabels(feature_df_MTGR, condition_pick, map_df)
x_levels <- unname(x_lab_map[c("4","2")])

fill_vals <- c("#02c39a", "#ff758f")
names(fill_vals) <- x_levels

p_MTGR <- plot_half_violin_subjects(
  behavior_df = be_df,
  feature_df  = feature_df_MTGR,
  condition_pick = condition_pick,
  map_df = map_df,
  subjects_order = c("4","2"),
  fill_vals = fill_vals,
  itpc_cols = c(Delta = "Delta_bandITPC", Theta = "Theta_bandITPC")
)

print(p_MTGR)
```

### Save
```{r}
ggsave(
    filename = "figures/06_ieeg/MTGR.pdf",
    plot = p_MTGR,
    width = 9, height = 7, units = "in",
    device = cairo_pdf,
    family = "Arial",
    bg = "white"
  )
```


